### ISSUE TITLE
Creating BUGs in the AzureDevops Backlog Using Sonarqube Issues

### ISSUE THREAD

**Issue by har2103** [apulko/Sonar2PBI#1]
Hi,

I have got an requirement to create a bug from sonarQube. I saw this post (https://medium.com/swlh/creating-bugs-in-the-azuredevops-backlog-using-sonarqube-issues-9781c9e2e2d7)
 and i am trying to follow that However i am missing some details can you please help me provide the details.

for Step 3:  Trigger the ‘BUG Creator’ pipeline when a Sonarqube analysis is finished.
Create a logic App, add a ‘When a HTTP request is received’ trigger. 

Can you please share the "**Request Body JSON Schema**" . That will be helpful.

Thanks.

**Comment by apulko** [comment]
Sorry for the late response. I hope it helps.

`{
    "properties": {
        "analysedAt": {
            "type": "string"
        },
        "project": {
            "properties": {
                "key": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "properties": {
            "properties": {},
            "type": "object"
        },
        "qualityGate": {
            "properties": {
                "conditions": {
                    "items": {
                        "properties": {
                            "errorThreshold": {
                                "type": "string"
                            },
                            "metric": {
                                "type": "string"
                            },
                            "onLeakPeriod": {
                                "type": "boolean"
                            },
                            "operator": {
                                "type": "string"
                            },
                            "status": {
                                "type": "string"
                            },
                            "value": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "errorThreshold",
                            "metric",
                            "onLeakPeriod",
                            "operator",
                            "status"
                        ],
                        "type": "object"
                    },
                    "type": "array"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "revision": {
            "type": "string"
        },
        "serverUrl": {
            "type": "string"
        },
        "status": {
            "type": "string"
        },
        "taskId": {
            "type": "string"
        }
    },
    "type": "object"
}`
